"""
nl_schema.py — Core dataclasses for the natural-language Hamiltonian interface.

These schemas form the foundation of the NL frontend layer; they are consumed
by the parser, inference engine, and report generator in later steps.
No business logic lives here — only typed data containers.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class ParsedHamiltonian:
    """
    Structured output of the natural-language parser.

    Represents a single attempt to interpret a free-text Hamiltonian description.
    Fields are populated incrementally: the parser fills ``family`` and ``params``,
    later stages add ``supported`` / ``confidence`` / ``warnings``.
    """

    raw_text: str
    """The original user-supplied description, preserved verbatim."""

    family: Optional[str] = None
    """Canonical family name (e.g. ``"tfim"``), or ``None`` if unrecognised."""

    params: Dict[str, float] = field(default_factory=dict)
    """Parsed physical parameters keyed by the codebase convention (e.g. ``{"J": 1.0, "h": 0.5}``)."""

    n_qubits: Optional[int] = None
    """System size, if explicitly stated or inferable from the description."""

    boundary: str = "obc"
    """Boundary condition string; ``"obc"`` (open) is the only currently supported value."""

    supported: bool = False
    """True iff ``family`` maps to a family in the registry that the pipeline can handle."""

    confidence: float = 0.0
    """Parser confidence in [0, 1]; 1.0 means unambiguous, 0.0 means pure guess."""

    warnings: List[str] = field(default_factory=list)
    """Non-fatal issues encountered during parsing (e.g. missing parameters, ambiguous phrasing)."""


@dataclass
class PropertyResult:
    """
    Physical observables computed for a specific Hamiltonian instance.

    Populated by the inference / estimation layer after a ``ParsedHamiltonian``
    has been validated and dispatched to the ShadowGPT pipeline.
    All observable fields are optional — they are ``None`` when not estimated.
    """

    family: str
    """Canonical family name, echoed from the corresponding ``ParsedHamiltonian``."""

    params: Dict[str, float] = field(default_factory=dict)
    """Parameters used in the computation (after defaults have been resolved)."""

    n_qubits: int = 0
    """System size used in the computation."""

    magnetization: Optional[float] = None
    """Average magnetisation ⟨Z⟩ per site."""

    correlations: Optional[float] = None
    """Nearest-neighbour two-point correlator (family-specific definition)."""

    energy: Optional[float] = None
    """Ground-state energy per site (or total, depending on context)."""

    renyi2_entropy: Optional[float] = None
    """Second Rényi entropy of the half-chain reduced density matrix."""

    notes: List[str] = field(default_factory=list)
    """Human-readable remarks about the estimation (e.g. method used, caveats)."""


@dataclass
class ExplanationResult:
    """
    Natural-language explanation of a ``PropertyResult``.

    Generated by the report layer; contains both a brief summary suitable for
    display in a single line and a longer explanation for detailed output.
    """

    short_summary: str = ""
    """One-sentence summary of the main physical finding."""

    detailed_summary: str = ""
    """Multi-sentence explanation covering all computed observables and caveats."""

    warnings: List[str] = field(default_factory=list)
    """Warnings surfaced during explanation generation (e.g. low confidence, missing fields)."""


__all__ = [
    "ParsedHamiltonian",
    "PropertyResult",
    "ExplanationResult",
]
