"""
report_generator.py — Deterministic natural-language explanation layer.

Converts a ``PropertyResult`` (from the exact or learned ShadowGPT backend)
into human-readable summaries and structured ``ExplanationResult`` objects.
All output is template-based; no LLM is involved.

Public API
----------
make_short_summary(result)       → one-to-two sentence high-level summary.
make_detailed_summary(result)    → multi-sentence explanation of all observables.
make_explanation_result(result)  → ExplanationResult combining both + warnings.

Convenience wrappers (parse → infer → report):
explain_exact(text)              → ExplanationResult via exact backend.
explain_with_shadowgpt(text, **) → ExplanationResult via learned backend.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Tuple

from .nl_schema import ExplanationResult, PropertyResult
from .family_registry import get_family_spec


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# Physical interpretation thresholds
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

# |magnetization| buckets
_MAG_NEAR_ZERO   = 0.05   # below this → "little net magnetization"
_MAG_WEAK        = 0.30   # below this → "weak net magnetization"
                           # above → "significant net magnetization"

# |ZZ correlation| buckets
_CORR_VERY_WEAK  = 0.10
_CORR_MODEST     = 0.30

# Rényi-2 entropy buckets (nats)
_S2_NEAR_PRODUCT = 0.10   # below → "near-product state"
_S2_MODERATE     = 0.50   # below → "moderate entanglement"
                           # above → "significant entanglement"

# TFIM: criticality is at |h/J| = 1 in the thermodynamic limit.
# Flag when within this fractional band of the critical point.
_TFIM_CRITICAL_TOL = 0.15


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# Backend detection
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

def _detect_backend(notes: List[str]) -> str:
    """
    Infer which backend produced *result* by scanning its notes.

    Returns ``"exact"``, ``"shadowgpt"``, or ``"unknown"``.
    """
    for note in notes:
        low = note.lower()
        if "exact diagonalization" in low:
            return "exact"
        if "shadowgpt" in low or "autoregressive" in low or "generated shadows" in low:
            return "shadowgpt"
    return "unknown"


def _backend_phrase(backend: str) -> str:
    """Return a short source-attribution phrase for inline use."""
    if backend == "exact":
        return "computed by exact diagonalization"
    if backend == "shadowgpt":
        return "estimated from synthetic shadows generated by the ShadowGPT model"
    return "computed"


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# Family description
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

def _describe_family(family: str, params: Dict[str, float], n_qubits: int) -> str:
    """
    Return a plain-English sentence identifying the Hamiltonian.

    Uses the registry's ``short_description`` plus a formatted parameter list.
    Falls back to a generic sentence if the family is not in the registry.
    """
    spec = get_family_spec(family)

    # Build a readable parameter string: "J=1.00, h=0.80"
    param_str = ", ".join(f"{k}={v:.2f}" for k, v in sorted(params.items()))

    if spec is not None:
        # Use the first sentence of short_description (up to first full stop).
        desc_sentence = spec.short_description.split(".")[0].strip()
        return (
            f"This is a {n_qubits}-qubit {desc_sentence} "
            f"with parameters {param_str} and open boundary conditions."
        )

    return (
        f"This is a {n_qubits}-qubit '{family}' Hamiltonian "
        f"with parameters {param_str} and open boundary conditions."
    )


def _tfim_phase_note(params: Dict[str, float]) -> Optional[str]:
    """
    Return a one-sentence note about the TFIM phase, or None.

    Remarks on the ferromagnetic / paramagnetic / near-critical regime based
    on the ratio |h/J|.  Only meaningful for TFIM.
    """
    J = params.get("J", 1.0)
    h = params.get("h", 0.5)
    if J == 0.0:
        return None
    ratio = abs(h / J)
    if abs(ratio - 1.0) <= _TFIM_CRITICAL_TOL:
        return (
            f"With |h/J| = {ratio:.2f}, the system is near the quantum critical point "
            f"(|h/J| = 1), where the model transitions between ferromagnetic and "
            f"paramagnetic phases."
        )
    if ratio < 1.0:
        return (
            f"With |h/J| = {ratio:.2f} < 1, the system is in the ferromagnetic phase, "
            f"where ZZ ordering tends to dominate over transverse-field fluctuations."
        )
    return (
        f"With |h/J| = {ratio:.2f} > 1, the system is in the paramagnetic phase, "
        f"where the transverse field dominates and spins tend to align along X."
    )


def _xxz_phase_note(params: Dict[str, float]) -> Optional[str]:
    """Return a brief XXZ phase note based on delta."""
    delta = params.get("delta", 1.0)
    if abs(delta) < 0.05:
        return "With delta ≈ 0, this reduces to the XX model (no ZZ anisotropy)."
    if abs(delta - 1.0) < 0.05:
        return "With delta = 1, this is the isotropic Heisenberg (XXX) chain."
    if delta < 0.0:
        return (
            f"With delta = {delta:.2f} < 0, ZZ interactions are antiferromagnetic "
            f"relative to the XX/YY terms."
        )
    return (
        f"With delta = {delta:.2f}, the model has enhanced ZZ anisotropy "
        f"relative to the XX/YY exchange."
    )


def _heisenberg_phase_note(params: Dict[str, float]) -> Optional[str]:
    """Return a brief Heisenberg phase note based on J sign."""
    J = params.get("J", 1.0)
    if J > 0:
        return (
            f"With J = {J:.2f} > 0, the chain is antiferromagnetic; "
            f"adjacent spins prefer to anti-align."
        )
    if J < 0:
        return (
            f"With J = {J:.2f} < 0, the chain is ferromagnetic; "
            f"adjacent spins prefer to align."
        )
    return None


def _family_phase_note(family: str, params: Dict[str, float]) -> Optional[str]:
    """Dispatch to the correct per-family phase note helper."""
    if family == "tfim":
        return _tfim_phase_note(params)
    if family == "xxz":
        return _xxz_phase_note(params)
    if family == "heisenberg":
        return _heisenberg_phase_note(params)
    return None


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# Observable description helpers
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

def _describe_energy(
    energy: Optional[float],
    family: str,
    n_qubits: int,
) -> Optional[str]:
    """
    Return a plain-English sentence describing the ground-state energy, or None.
    """
    if energy is None:
        return None
    per_site = energy / n_qubits if n_qubits > 0 else energy
    return (
        f"The ground-state energy is {energy:.4f} "
        f"(approximately {per_site:.4f} per site for {n_qubits} qubits)."
    )


def _describe_magnetization(
    magnetization: Optional[float],
    family: str,
    params: Dict[str, float],
) -> Optional[str]:
    """
    Return a plain-English sentence describing the average Z magnetization, or None.
    """
    if magnetization is None:
        return None
    m = magnetization
    abs_m = abs(m)
    sign_phrase = "positive" if m > 0 else ("negative" if m < 0 else "zero")

    if abs_m < _MAG_NEAR_ZERO:
        qualitative = "little net magnetization along Z (consistent with a disordered or balanced state)"
    elif abs_m < _MAG_WEAK:
        qualitative = f"weak {sign_phrase} net magnetization along Z"
    else:
        qualitative = f"significant {sign_phrase} net magnetization along Z"

    # Add family-specific context for hz (longitudinal field polarizes spins)
    hz_note = ""
    if family == "ising_general":
        hz = params.get("hz", 0.0)
        if abs(hz) > 0.05:
            direction = "positive" if hz > 0 else "negative"
            hz_note = (
                f" The longitudinal field hz = {hz:.2f} tends to polarize spins "
                f"in the {direction} Z direction."
            )

    return (
        f"The average Z magnetization is {m:.4f}, indicating {qualitative}.{hz_note}"
    )


def _describe_correlations(
    correlations: Optional[float],
    family: str,
    n_qubits: int,
) -> Optional[str]:
    """
    Return a plain-English sentence describing nearest-neighbor ZZ correlations, or None.
    """
    if correlations is None:
        return None
    if n_qubits < 2:
        return "Nearest-neighbor correlations are not defined for a single-qubit system."

    c = correlations
    abs_c = abs(c)
    sign_phrase = "ferromagnetic (positive ZZ)" if c > 0 else "antiferromagnetic (negative ZZ)"

    if abs_c < _CORR_VERY_WEAK:
        strength = "very weak"
    elif abs_c < _CORR_MODEST:
        strength = "modest"
    else:
        strength = "relatively strong"

    return (
        f"The average nearest-neighbor ZZ correlation is {c:.4f}, "
        f"which is {strength} and {sign_phrase} in character."
    )


def _describe_renyi2(
    renyi2_entropy: Optional[float],
    n_qubits: int,
) -> Optional[str]:
    """
    Return a plain-English sentence describing the Rényi-2 half-chain entropy, or None.
    """
    if renyi2_entropy is None:
        return None
    s2 = renyi2_entropy
    k = max(1, n_qubits // 2)

    if s2 < _S2_NEAR_PRODUCT:
        qualitative = (
            "very small, suggesting the state is close to a product state "
            "with little quantum entanglement across the bipartition"
        )
    elif s2 < _S2_MODERATE:
        qualitative = (
            "moderate, indicating a nontrivial degree of quantum entanglement "
            "across the bipartition"
        )
    else:
        qualitative = (
            "relatively large, indicating significant quantum entanglement "
            "across the bipartition"
        )

    return (
        f"The Rényi-2 entropy of the half-chain bipartition "
        f"(first {k} of {n_qubits} qubits) is {s2:.4f}, which is {qualitative}."
    )


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# Warning extraction from notes
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

# Keywords in notes that should be surfaced as warnings.
# Each entry is (substring_to_match, warning_prefix).
_WARNING_TRIGGERS: List[Tuple[str, str]] = [
    ("snap",     "Parameter snapping occurred"),
    ("failed",   "Estimation failure"),
    ("skipped",  "Observable skipped"),
    ("warning",  "Backend warning"),
    ("extrapolat", "Potential extrapolation"),
    ("may not have been trained", "Out-of-distribution risk"),
]

_SHADOWGPT_GENERAL_CAVEAT = (
    "Results were estimated from synthetic shadows generated by the learned ShadowGPT "
    "model, not from the exact quantum state. Estimates carry statistical uncertainty "
    "and depend on how well the training distribution covers these parameters."
)


def _collect_warnings_from_notes(notes: List[str], backend: str) -> List[str]:
    """
    Scan *notes* and return a list of human-readable warning strings.

    Rules:
    - Any note matching a ``_WARNING_TRIGGERS`` keyword is surfaced with a
      standardised prefix.
    - If the backend is ``"shadowgpt"``, append a general learned-model caveat.
    - Each warning is de-duplicated by prefix so repeat triggers do not flood.
    """
    warnings: List[str] = []
    seen_prefixes: set = set()

    for note in notes:
        low = note.lower()
        for keyword, prefix in _WARNING_TRIGGERS:
            if keyword in low and prefix not in seen_prefixes:
                seen_prefixes.add(prefix)
                warnings.append(f"{prefix}: {note.strip()}")

    if backend == "shadowgpt" and _SHADOWGPT_GENERAL_CAVEAT not in warnings:
        warnings.append(_SHADOWGPT_GENERAL_CAVEAT)

    return warnings


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# Public: make_short_summary
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

def make_short_summary(result: PropertyResult) -> str:
    """
    Return a one-to-two sentence high-level summary of *result*.

    Covers:
    - Hamiltonian family and key parameters.
    - The most physically informative available observable (energy, then
      magnetization, then correlations).
    - Source attribution (exact vs. ShadowGPT).

    Parameters
    ----------
    result : PropertyResult
        Populated result object from the exact or learned backend.

    Returns
    -------
    str
        One-to-two sentence plain-English summary.
    """
    family     = result.family
    params     = result.params
    n_qubits   = result.n_qubits
    backend    = _detect_backend(result.notes)
    back_phrase = _backend_phrase(backend)

    # Identify the Hamiltonian briefly.
    spec = get_family_spec(family)
    family_label = spec.canonical_name.upper() if spec else family.upper()

    param_str = ", ".join(f"{k}={v:.2f}" for k, v in sorted(params.items()))
    id_clause = f"{n_qubits}-qubit {family_label} ({param_str})"

    # Pick the most informative single observable for the short summary.
    obs_clause = ""
    if result.energy is not None:
        per_site = result.energy / n_qubits if n_qubits > 0 else result.energy
        obs_clause = (
            f"The ground-state energy is {result.energy:.4f} "
            f"({per_site:.4f} per site)."
        )
    elif result.magnetization is not None:
        m = result.magnetization
        abs_m = abs(m)
        if abs_m < _MAG_NEAR_ZERO:
            mag_desc = "little net Z magnetization"
        elif abs_m < _MAG_WEAK:
            mag_desc = f"weak Z magnetization ({m:.3f})"
        else:
            mag_desc = f"significant Z magnetization ({m:.3f})"
        obs_clause = f"The system shows {mag_desc}."
    elif result.correlations is not None:
        c = result.correlations
        abs_c = abs(c)
        if abs_c < _CORR_VERY_WEAK:
            corr_desc = "very weak nearest-neighbor ZZ correlations"
        elif abs_c < _CORR_MODEST:
            corr_desc = "modest nearest-neighbor ZZ correlations"
        else:
            corr_desc = "relatively strong nearest-neighbor ZZ correlations"
        obs_clause = f"The system shows {corr_desc} ({c:.3f})."

    summary = f"Ground-state properties of the {id_clause}, {back_phrase}."
    if obs_clause:
        summary = f"{summary} {obs_clause}"
    return summary


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# Public: make_detailed_summary
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

def make_detailed_summary(result: PropertyResult) -> str:
    """
    Return a multi-sentence detailed explanation of all observables in *result*.

    Structure:
    1. Hamiltonian identity sentence.
    2. Family-specific physical context (phase, regime).
    3. Energy sentence (if available).
    4. Magnetization sentence (if available).
    5. Correlations sentence (if available).
    6. Rényi-2 entropy sentence (if available).
    7. Backend attribution sentence.

    Parameters
    ----------
    result : PropertyResult
        Populated result object from the exact or learned backend.

    Returns
    -------
    str
        Multi-sentence plain-English explanation.
    """
    family   = result.family
    params   = result.params
    n_qubits = result.n_qubits
    backend  = _detect_backend(result.notes)

    sentences: List[str] = []

    # 1. Hamiltonian identity
    sentences.append(_describe_family(family, params, n_qubits))

    # 2. Family-specific physical context
    phase_note = _family_phase_note(family, params)
    if phase_note:
        sentences.append(phase_note)

    # 3–6. Observable sentences
    energy_sent = _describe_energy(result.energy, family, n_qubits)
    if energy_sent:
        sentences.append(energy_sent)

    mag_sent = _describe_magnetization(result.magnetization, family, params)
    if mag_sent:
        sentences.append(mag_sent)

    corr_sent = _describe_correlations(result.correlations, family, n_qubits)
    if corr_sent:
        sentences.append(corr_sent)

    renyi_sent = _describe_renyi2(result.renyi2_entropy, n_qubits)
    if renyi_sent:
        sentences.append(renyi_sent)

    # 7. Backend attribution
    back_phrase = _backend_phrase(backend)
    if backend == "exact":
        sentences.append(
            f"All values were {back_phrase} (numpy.linalg.eigh), "
            f"which is numerically exact for systems of this size."
        )
    elif backend == "shadowgpt":
        n_shadows_note = ""
        for note in result.notes:
            if "n_shadows=" in note:
                import re
                m = re.search(r"n_shadows=(\d+)", note)
                if m:
                    n_shadows_note = f" using {m.group(1)} synthetic shadow measurements"
                    break
        sentences.append(
            f"All values were {back_phrase}{n_shadows_note}. "
            f"Shadow-based estimates carry statistical uncertainty."
        )
    else:
        sentences.append(f"Values were {back_phrase}.")

    return " ".join(sentences)


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# Public: make_explanation_result
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

def make_explanation_result(result: PropertyResult) -> ExplanationResult:
    """
    Convert *result* into a fully populated ``ExplanationResult``.

    Calls ``make_short_summary``, ``make_detailed_summary``, and
    ``_collect_warnings_from_notes`` and assembles the schema object.

    Parameters
    ----------
    result : PropertyResult
        Output of ``evaluate_exact`` or ``evaluate_with_shadowgpt``.

    Returns
    -------
    ExplanationResult
        With ``short_summary``, ``detailed_summary``, and ``warnings`` populated.
    """
    backend  = _detect_backend(result.notes)
    short    = make_short_summary(result)
    detailed = make_detailed_summary(result)
    warnings = _collect_warnings_from_notes(result.notes, backend)
    return ExplanationResult(
        short_summary=short,
        detailed_summary=detailed,
        warnings=warnings,
    )


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# Convenience wrappers: parse → infer → report
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

def explain_exact(text: str) -> ExplanationResult:
    """
    Parse *text*, run exact diagonalization, and return an ``ExplanationResult``.

    Equivalent to::

        result = parse_and_evaluate_exact(text)
        return make_explanation_result(result)

    Parameters
    ----------
    text : str
        Free-text Hamiltonian description, e.g. ``"4-qubit TFIM J=1 h=0.8"``.

    Returns
    -------
    ExplanationResult

    Raises
    ------
    ValueError
        If the description cannot be parsed into a fully supported Hamiltonian.
    """
    from .inference_engine import parse_and_evaluate_exact

    result = parse_and_evaluate_exact(text)
    return make_explanation_result(result)


def explain_with_shadowgpt(text: str, **kwargs) -> ExplanationResult:
    """
    Parse *text*, run the ShadowGPT learned backend, and return an ``ExplanationResult``.

    Equivalent to::

        result = parse_and_evaluate_with_shadowgpt(text, **kwargs)
        return make_explanation_result(result)

    Keyword arguments are forwarded to ``evaluate_with_shadowgpt``
    (``checkpoint_dir``, ``n_shadows``, ``temperature``, ``device``, ``seed``).

    Parameters
    ----------
    text : str
        Free-text Hamiltonian description.

    Returns
    -------
    ExplanationResult

    Raises
    ------
    ImportError
        If PyTorch is not installed.
    ValueError
        If the description cannot be parsed.
    FileNotFoundError
        If the checkpoint directory is not found.
    """
    from .inference_engine import parse_and_evaluate_with_shadowgpt

    result = parse_and_evaluate_with_shadowgpt(text, **kwargs)
    return make_explanation_result(result)


__all__ = [
    "make_short_summary",
    "make_detailed_summary",
    "make_explanation_result",
    "explain_exact",
    "explain_with_shadowgpt",
]
